services:
  server:
    image: comic-center-server
    pull_policy: never
    build:
      context: ./server
      dockerfile: dockerfile.local      
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: comic_center
    env_file:
      - ./database/.env
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes: 
 postgres_data: